[package]
name = "blog-20250111-async-perf-locks"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["async_tokio", "async_std"] }
crossbeam = "0.8.4"
tokio = { version = "1.43.0", features = ["full"] }

[[bench]]
name = "benchmark"
harness = false
